#!/usr/bin/env bash
#
# Install the Adventure Game as an agent skill.
#
# Two jobs, and the second is the one that matters:
#   1. symlink this repo into the agent's skills directory
#   2. put `adventure-game` / `adventure-doctor` launchers on PATH, so the
#      engine runs from any working directory — without them the agent has
#      to hunt the filesystem for game.py on every cold session.
#
# Safe to re-run: it refreshes the symlink and rewrites the launchers.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
HERMES_BASE="${HERMES_HOME:-$HOME/.hermes}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
SKILL_NAME="adventure-game-host"
SKILLS_DIR=""
PROFILE=""
PYTHON=""
MAKE_BIN=1

usage() {
  cat <<'USAGE'
Usage: ./install.sh [options]

Where to install the skill (pick one; auto-detected if omitted):
  --profile NAME     into ~/.hermes/profiles/NAME/skills/
  --global           into ~/.hermes/skills/
  --skills-dir DIR   into an explicit directory (any SKILL.md-style host,
                     e.g. ~/.claude/skills)

Launchers:
  --bin-dir DIR      where to write adventure-game / adventure-doctor
                     (default: ~/.local/bin)
  --no-bin           skip the launchers entirely

Other:
  --python PATH      interpreter for the launchers
                     (default: ./.venv/bin/python if present, else python3)
  -h, --help         this message
USAGE
}

say()  { printf '  %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }
die()  { printf '\nerror: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --profile)    PROFILE="${2:-}"; [ -n "$PROFILE" ] || die "--profile needs a name"; shift 2 ;;
    --global)     SKILLS_DIR="$HERMES_BASE/skills"; shift ;;
    --skills-dir) SKILLS_DIR="${2:-}"; [ -n "$SKILLS_DIR" ] || die "--skills-dir needs a path"; shift 2 ;;
    --bin-dir)    BIN_DIR="${2:-}"; [ -n "$BIN_DIR" ] || die "--bin-dir needs a path"; shift 2 ;;
    --no-bin)     MAKE_BIN=0; shift ;;
    --python)     PYTHON="${2:-}"; [ -n "$PYTHON" ] || die "--python needs a path"; shift 2 ;;
    -h|--help)    usage; exit 0 ;;
    *)            usage >&2; die "unknown option: $1" ;;
  esac
done

echo
echo "Hermes Adventure Game — install"
echo "  repo: $REPO_ROOT"

# --- 1. where does the skill go? ------------------------------------------

if [ -n "$PROFILE" ]; then
  [ -d "$HERMES_BASE/profiles/$PROFILE" ] || die "no such profile: $HERMES_BASE/profiles/$PROFILE"
  SKILLS_DIR="$HERMES_BASE/profiles/$PROFILE/skills"
fi

if [ -z "$SKILLS_DIR" ]; then
  # Profiles each have their own skills dir; guessing between several would
  # silently install where the agent isn't looking, so ask instead.
  profiles=""
  profile_count=0
  if [ -d "$HERMES_BASE/profiles" ]; then
    for d in "$HERMES_BASE"/profiles/*/; do
      [ -d "$d" ] || continue
      profiles="$profiles $(basename "$d")"
      profile_count=$((profile_count + 1))
    done
  fi
  case "$profile_count" in
    0) SKILLS_DIR="$HERMES_BASE/skills" ;;
    1) SKILLS_DIR="$HERMES_BASE/profiles/${profiles# }/skills" ;;
    *) die "several Hermes profiles found -->$profiles
       re-run with --profile NAME (per-profile), --global (all profiles),
       or --skills-dir DIR" ;;
  esac
fi

# --- 2. interpreter -------------------------------------------------------

if [ -z "$PYTHON" ]; then
  if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
    PYTHON="$REPO_ROOT/.venv/bin/python"
  else
    PYTHON="$(command -v python3 || command -v python || true)"
  fi
fi
[ -n "$PYTHON" ] || die "no python found — pass --python PATH"
say "python: $PYTHON"

if ! "$PYTHON" -c 'import pydantic' >/dev/null 2>&1; then
  warn "pydantic is not importable by that interpreter; the engine won't run until:"
  warn "    $PYTHON -m pip install -r '$REPO_ROOT/requirements.txt'"
fi

# --- 3. symlink the skill -------------------------------------------------

mkdir -p "$SKILLS_DIR"
link="$SKILLS_DIR/$SKILL_NAME"
if [ -L "$link" ]; then
  ln -sfn "$REPO_ROOT" "$link"
  say "skill:  $link (symlink refreshed)"
elif [ -e "$link" ]; then
  die "$link already exists and is not a symlink — move it aside first"
else
  ln -s "$REPO_ROOT" "$link"
  say "skill:  $link"
fi

# --- 4. launchers ---------------------------------------------------------

if [ "$MAKE_BIN" -eq 1 ]; then
  mkdir -p "$BIN_DIR"
  for pair in "adventure-game:game.py" "adventure-doctor:doctor.py"; do
    name="${pair%%:*}"
    script="${pair##*:}"
    target="$BIN_DIR/$name"
    cat > "$target" <<EOF
#!/bin/sh
# Generated by HermesAdventureGame/install.sh — re-run it to update.
exec "$PYTHON" "$REPO_ROOT/scripts/$script" "\$@"
EOF
    chmod +x "$target"
    say "launcher: $target"
  done

  case ":${PATH:-}:" in
    *":$BIN_DIR:"*) ;;
    *) warn "$BIN_DIR is not on your PATH — add it, or the agent won't find the launchers:"
       warn "    export PATH=\"\$PATH:$BIN_DIR\"" ;;
  esac
else
  warn "launchers skipped (--no-bin): SKILL.md's commands assume adventure-game is on PATH"
fi

# --- 5. verify ------------------------------------------------------------

if [ "$MAKE_BIN" -eq 1 ] && "$BIN_DIR/adventure-game" --help >/dev/null 2>&1; then
  say "verified: adventure-game runs"
fi

cat <<EOF

Done. Start a new agent session (skills are loaded at session start), then say
"let's play the adventure game".

  save file:  $REPO_ROOT/data/hermes_game.db
  inspect:    adventure-doctor -v
EOF
