"""Static configuration and seed content for a new game.

See TECHNICAL_DETAILS.md §1 ("Seed content") for the rationale: only the
starting room is handcrafted here. Everything else is generated by Hermes
Agent at play time via `scripts/game.py create-room`.
"""

import os

# HERMES_DB_PATH lets the test suite point subprocess-driven CLI runs at a
# throwaway file instead of the real save; unset in normal play.
# Relative to the skill directory (the CLI's cwd), not to this file — kept
# out of scripts/ so the save is runtime state, not source.
DB_PATH = os.environ.get("HERMES_DB_PATH", "data/hermes_game.db")

# How many recent turn_log rows `scripts/game.py state` includes for narrative
# continuity (TECHNICAL_DETAILS.md §3.5).
RECENT_TURNS_LIMIT = 6

STARTING_HP = 100

# Seed zone (game_config) — from PLAN.md Phase 4's example prompt.
ZONE_NAME = "Mechanical Spire"
ZONE_DESCRIPTION = (
    "An ancient, vertical labyrinth of clockwork gears and leaking steam."
)
GLOBAL_THEME_RULES = (
    "Rooms are mechanical, industrial, and vertical: gears, pipes, steam, "
    "rust, and clockwork machinery. Avoid organic, magical, or modern "
    "elements. Every room should feel like part of one continuous, ancient "
    "engineering structure."
)

# Seed starting room at (0, 0, 0) — from TECHNICAL_DETAILS.md §1.
START_ROOM_NAME = "Rust-Chamber"
START_ROOM_DESCRIPTION = (
    "Steam hisses from corroded wall pipes overhead, drifting across a floor "
    "of rusted steel grating. The chamber groans faintly with the distant "
    "rhythm of unseen machinery."
)
START_ROOM_EXITS = ["north", "east", "up"]
